[build]
  command = "node netlify/build/version.js"
  publish = "."
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "18"

[functions]
  node_bundler = "esbuild"

[[redirects]]
  from = "/admin"
  to = "/admin-listings.html"
  status = 200
  force = true

[[redirects]]
  from = "/admin-listings"
  to = "/admin-listings.html"
  status = 200
  force = true

[[redirects]]
  from = "/admin-settings"
  to = "/admin-listings.html"
  status = 200
  force = true

[[redirects]]
  from = "/about"
  to = "/about.html"
  status = 200

[[redirects]]
  from = "/events"
  to = "/events.html"
  status = 200
