[build]
  publish = "."
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "18"

[functions]
  node_bundler = "esbuild"

[[redirects]]
  from = "/admin"
  to = "/admin-listings.html"
  status = 200

[[redirects]]
  from = "/admin-listings"
  to = "/admin-listings.html"
  status = 200

[[redirects]]
  from = "/admin-settings"
  to = "/admin.html"
  status = 200

[[redirects]]
  from = "/about"
  to = "/about.html"
  status = 200
